language: objective-c

script:
- set -o pipefail && xcodebuild test -workspace Example/MSProgressSlider.xcworkspace -scheme MSProgressSlider-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
